--
CREATE SEQUENCE IF NOT EXISTS public.advertisers_advertiser_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;



create table public.advertisers
(
    advertiser_id                    integer       not null DEFAULT nextval('advertisers_advertiser_id_seq'::regclass) primary key,
    company_name                     varchar(256)                                                             not null,
    contact_first_name               varchar(128),
    contact_last_name                varchar(128),
    email                            varchar(192),
    primary_phone                    varchar(12),
    cell                             varchar(12),
    address1                         varchar(256),
    address2                         varchar(256),
    city                             varchar(256),
    state                            char(2),
    zip                              varchar(12),
    active                           boolean       default true                                               not null,
    time_zone                        text                                                                     not null,
    account_manager_user_id          integer,
    coremetrics_id                   varchar(10),
    strict_control_group             boolean,
    appnexus_segment_id              integer,
    piggyback_request                integer       default 2                                                  not null,
    click_conversion_window          interval(6)   default '30 days'::interval                                not null,
    allow_duplicate_orders           boolean       default false                                              not null,
    segmentation_active              boolean       default false                                              not null,
    create_time                      timestamp(6)  default now()                                              not null,
    abandon_window                   interval(6)   default '2 days'::interval                                 not null,
    invoice_conversion_window        interval(6)   default '30 days'::interval                                not null,
    control_group_percentage         numeric(2, 2) default 0.1                                                not null,
    strict_control_group_requests    integer,
    segmentation_new_active          boolean       default false                                              not null,
    currency                         text          default 'USD'::text,
    google_audience_id               text,
    segment_piggyback                boolean       default false                                              not null,
    client_id                        integer,
    pixel_id                         integer,
    watermarked                      boolean       default true                                               not null,
    tier                             integer,
    pixel_id_conversion              integer,
    display_currency                 varchar(3)    default 'USD'::character varying                           not null,
    locale                           varchar(64)   default 'en-US'::character varying                         not null,
    piggyback_tier_active            boolean       default false                                              not null,
    dpp_enabled                      boolean       default true                                               not null,
    override_tt_campaign_check       boolean       default true                                               not null,
    event_logging_enabled            boolean       default true                                               not null,
    trpx_endpoint                    integer,
    slingshot_window                 integer       default 86400                                              not null,
    slingshot_enabled                boolean       default true                                               not null,
    min_control_rt                   integer       default 0                                                  not null,
    min_control_rto                  integer       default 0                                                  not null,
    min_control_branding             integer       default 0                                                  not null,
    spx_timeout_ms                   integer       default 0,
    populate_order_on_conversion     boolean       default false                                              not null,
    facebook_page                    text,
    facebook_page_id                 bigint,
    week_start_day                   smallint      default 0                                                  not null,
    clickpass_enabled                boolean       default true                                               not null,
    clickpass_click_ttl              interval(6)   default '01:00:00'::interval                               not null,
    clickpass_view_ttl               interval(6)   default '00:31:00'::interval                               not null,
    clickpass_target_tag_id          smallint      default 2784,
    clickpass_iframe_ttl             integer       default 10000                                              not null,
    clickpass_window                 interval(6)   default '01:00:00'::interval                               not null,
    just_registered_clickpass_ttl    integer       default 10                                                 not null,
    clickpass_iframe_delay           integer       default 0                                                  not null,
    blended_fbx_enabled              boolean       default false,
    blended_fbx_setup                boolean       default false,
    blended_fbx_click_url            text,
    blended_fbx_headline             text,
    blended_fbx_text                 text,
    clickpass_facebook_ttl           interval(6)   default '01:00:00'::interval,
    news_feed_weight                 integer       default 1,
    right_hand_side_weight           integer       default 4,
    fb_ad_account_id                 bigint,
    use_ss_cookies                   boolean       default false,
    clickpass_acquisition_ttl        interval(6)   default '24:00:00'::interval                               not null,
    postponed_clickpass              boolean       default false                                              not null,
    strict_clickpass                 boolean       default false                                              not null,
    adops_owner                      text          default ''::text,
    account_health                   text          default 'Normal'::text,
    publisher_enabled                boolean       default false,
    internal_cp_enabled              boolean       default true,
    apply_budget_to_total_spend      boolean       default false                                              not null,
    company_size                     text,
    industry                         text,
    billing_type_id                  integer,
    is_test                          boolean       default false,
    logo                             text,
    deleted                          boolean       default false,
    view_conversion_window           interval(6)   default '30 days'::interval,
    product_version_id               integer,
    has_products                     boolean       default false                                              not null,
    company_url                      text,
    update_time                      timestamp(6)  default now(),
    verify_email                     boolean       default false                                              not null,
    website_review_rejection         text,
    facebook_tos                     boolean       default false,
    tracking_pixel_status_id         integer       default 9,
    conversion_pixel_status_id       integer       default 9,
    website_review_status_id         integer       default 11,
    facebook_page_status_id          integer       default 9,
    country                          text,
    notify_me_of_additional_services boolean       default false,
    monthly_muv                      text,
    temp_login_token                 text,
    gdpr_status_id                   integer,
    conversion_window                interval(6)   default '30 days'::interval                                not null,
    data_tier_id                     integer       default 1,
    api_key                          text,
    allow_original_url_case          boolean       default false,
    ccpa_approval_time               timestamp,
    invoice_email                    text,
    status_id                        smallint,
    invoice_terms                    interval      default '30 days'::interval,
    user_id                          integer,
    utm_argument_ignore              boolean       default true,
    country_iso_code                 varchar(2)    default 'US'::character varying                            not null,
    gaclid_enabled                   boolean       default false                                              not null,
    advertiser_vertical_id           integer
);

alter table public.advertisers
    owner to qacore;
